import React, { useState, useEffect } from 'react';
import { RefreshCw, Play, TrendingUp } from 'lucide-react';
import { ForecastSummary, ForecastExplanation } from '../components/forecast/ForecastComponents';
import { ForecastChart } from '../components/charts/ForecastChart';
import { LoadingState, EmptyState } from '../components/common/States';
import { forecastApi } from '../services/api/forecastApi';

export const Forecast = () => {
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [forecast, setForecast] = useState(null);
  const [explanationOpen, setExplanationOpen] = useState(false);

  const fetchForecast = async () => {
    try {
      setLoading(true);
      const data = await forecastApi.getLatestForecast();
      setForecast(data);
    } catch (err) {
      console.error('Failed to load forecast:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchForecast();
  }, []);

  const handleGenerateForecast = async () => {
    try {
      setGenerating(true);
      const newFc = await forecastApi.generateForecast();
      setForecast(newFc);
    } catch (err) {
      console.error('Failed to generate forecast:', err);
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return <LoadingState message="Generating future 24-hour forecast from Transformer artifact..." />;
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-theme-text font-mono">
            24-Hour Energy Forecast
          </h2>
          <p className="text-xs text-theme-muted mt-0.5">
            Forward 48-step load projections at 30-minute intervals generated by the Multi-Scale Transformer.
          </p>
        </div>

        <button
          onClick={handleGenerateForecast}
          disabled={generating}
          className="btn-primary text-xs px-4 py-2 self-start sm:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${generating ? 'animate-spin' : ''}`} />
          <span>{generating ? 'Predicting Trajectory...' : 'Regenerate Forecast'}</span>
        </button>
      </div>

      {!forecast?.points || forecast.points.length === 0 ? (
        <EmptyState
          icon={TrendingUp}
          title="No forecast generated yet"
          description="Generate your first 24-hour energy trajectory based on recent historical telemetry."
          actionLabel="Generate 24-Hour Forecast"
          onAction={handleGenerateForecast}
        />
      ) : (
        <>
          {/* Summary Metric Cards with Inline Explain Toggle */}
          <ForecastSummary
            summary={forecast.summary}
            modelName={forecast.model_name}
            modelVersion={forecast.model_version}
            isExplanationOpen={explanationOpen}
            onToggleExplain={() => setExplanationOpen(!explanationOpen)}
          />

          {/* Inline Expandable Explanation (Captum Integrated Gradients) */}
          <ForecastExplanation
            explanations={forecast.explanations || []}
            isOpen={explanationOpen}
          />

          {/* 48-Point Time-Series Chart */}
          <div className="glass-panel p-6">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-sm font-bold text-theme-text uppercase tracking-wider">
                  Forecast Trajectory (kWh / 30 min)
                </h3>
                <p className="text-xs text-theme-muted">
                  Continuous 48-step prediction sequence across the 24-hour lookahead horizon.
                </p>
              </div>
              <span className="text-xs font-mono text-[var(--color-secondary)]">
                48 Steps • 30-Min Resolution
              </span>
            </div>

            <ForecastChart points={forecast.points} height={340} />
          </div>
        </>
      )}
    </div>
  );
};
